id: P008022
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:06.692957
source_metadata:
  id: bdr:W00EGS1016684
  title: སྤྲུལ་པའི་བསྟན་སྲུང་ཆེན་པོ་རྡོ་རྗེ་ཤུགས་ལྡན་རྩལ་ལས་འཕྲོས་པའི་རྩོད་ལན་ལེགས་བཤད་སྙིང་པོ
  author: ''
  volumes:
    09d42df76cb04535a9f75fc706d227f4:
      image_group_id: I1CZ5012
      title: Volume 1 of sprul pa'i bstan srung chen po rdo rje shugs ldan rtsal las
        'phros pa'i rtsod lan legs bshad snying po
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
