id: opecha:P008022
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016684
  title: སྤྲུལ་པའི་བསྟན་སྲུང་ཆེན་པོ་རྡོ་རྗེ་ཤུགས་ལྡན་རྩལ་ལས་འཕྲོས་པའི་རྩོད་ལན་ལེགས་བཤད་སྙིང་པོ
  volume: ''
  author: ''
