id: P008022
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016684
  title: སྤྲུལ་པའི་བསྟན་སྲུང་ཆེན་པོ་རྡོ་རྗེ་ཤུགས་ལྡན་རྩལ་ལས་འཕྲོས་པའི་རྩོད་ལན་ལེགས་བཤད་སྙིང་པོ
  author: ''
  volumes:
    3d6037ad7d694e0dbf1b52d275b8d4be:
      image_group_id: I1CZ5012
      title: ''
      volume_number: 1
      total_pages: 356
ebook_metadata:
  title: སྤྲུལ་པའི་བསྟན་སྲུང་ཆེན་པོ་རྡོ་རྗེ་ཤུགས་ལྡན་རྩལ་ལས་འཕྲོས་པའི་རྩོད་ལན་ལེགས་བཤད་སྙིང་པོ
  author: ''
  sku: P008022
  cover: cover.jpg
  layers:
  - pagination
